name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        ext: [linux-amd64, darwin-amd64, windows-amd64.exe]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -o=wp-checker-${{ matrix.ext }}

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.goos }}
          path: ./wp-checker-${{ matrix.ext }}
