name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o=wp-checker-linux-amd64

      - name: Archive production artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: binary-linux
          path: ./wp-checker-linux-amd64

  build-macos:
    name: Build macOS
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: GOOS=darwin GOARCH=amd64 go build -o=wp-checker-darwin-amd64

      - name: Archive production artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: binary-macos
          path: ./wp-checker-darwin-amd64

  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -o=wp-checker-windows-amd64.exe

      - name: Archive production artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: binary-windows
          path: ./wp-checker-windows-amd64.exe
