name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.38

